### ISSUE TITLE
Get data through interviews

### ISSUE THREAD

**Issue by Stephanie12138** [pzy1909/languagesbeakers#2]
### **Introduction**
In the previous investigation and research, the data collected was not complete and the user's needs could not be clearly analyzed. Therefore, we need a deeper investigation. We may do some interviews and survey. The purpose is to identify our target user group. In addition, the analysis of research data to confirm user needs to formulate the functions of our further products.

### **The members involved in this issue are**
@Stephanie12138
@pzy1909
@2331417368 
@TerrrrenceGong 

### **Task To Do**
- [x] Make a questionnaire @Stephanie12138 
- [x] Do some survey @2331417368 
- [x] Do some interview @pzy1909 
- [x] Analysis data that collected @TerrrrenceGong

**Comment by Stephanie12138** [comment]
Hi guys!
If you have time, it a good idea to upload the files involved.
Cheers~

**Comment by pzy1909** [comment]
OK I have already uploaded the record of the interview on wiki page.
